version: "3"
services:
  node-nest-project:
    build: .
    container_name: node-nest-project
    image: quyo/node-nest-project:latest
    restart: "no"
    networks:
      - external
    ports:
      - 3000:3000

networks:
  external:
    name: node-nest-project_external
